/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.gallery.agent

/**
 * Sealed hierarchy representing all lifecycle and streaming events emitted by
 * [AgentRuntimeExecutor].
 */
sealed interface AgentEvent {

  /**
   * Emitted when an agent turn or execution loop begins.
   *
   * @property request The request payload containing the user query, attachments, and metadata.
   */
  data class LoopInitiated(val request: AgentRequest) : AgentEvent

  /**
   * Emitted incrementally as the model generates text or reasoning tokens.
   *
   * @property token The newly streamed chunk of user-facing response text.
   * @property thinking Optional reasoning or chain-of-thought text generated by thinking models.
   * @property done Whether this token is the final token in the current streaming response.
   */
  data class StreamToken(
    val token: String,
    val thinking: String? = null,
    val done: Boolean = false,
  ) : AgentEvent

  /**
   * Emitted when an agent turn or execution loop completes naturally and successfully.
   *
   * @property finalResponse The complete, accumulated response text produced during the turn.
   */
  data class LoopTerminated(val finalResponse: String) : AgentEvent

  /**
   * Emitted when an agent turn is prematurely cancelled by the caller, indicating that all
   * underlying inference resources and background tasks have finished cleaning up.
   */
  data object LoopCancelled : AgentEvent

  /**
   * Emitted when an unrecoverable error occurs during inference or execution.
   *
   * @property errorMessage A human-readable description of the failure.
   */
  data class Error(val errorMessage: String) : AgentEvent
}
